### Create a new user
POST http://localhost:3000/auth/signup
content-type: application/json

{
  "email": "asdfg@asdfg.com",
  "password": "asdfg"
}

### Sign in as a existing user
POST http://localhost:3000/auth/signin
content-type: application/json

{
  "email": "asdfg@asdfg.com",
  "password": "asdfg"
}

### Get the currentl signed in user
GET http://localhost:3000/auth/whoami

### Sign out
POST http://localhost:3000/auth/signout

### Find a particular user with a given ID
GET http://localhost:3000/auth/2

### Find all users with a given email
GET http://localhost:3000/auth?email=asdf@asdf.com

### Update a user
PATCH  http://localhost:3000/auth/2
content-type: application/json

{
  "email": "fdsa@fdsa.com"
}

### Delete a user given ID
DELETE  http://localhost:3000/auth/1
